import express from "express";
import admin from "./admin.js";
import wechat from "./wechat.js";
import message from "./message.js";
import group from "./group.js";
import contact from "./contact.js";
import material from "./material.js";
import file from "./file.js";
import keyword from "./keyword.js";
import information from "./information.js";
import tag from "./tag.js";
import informationTag from "./information_tag.js";
import autoReply from "./auto_reply.js";
import roomInformation from "./room_information.js";
import bulkMessage from "./bulk_message.js";
const router = express.Router();
router.use('/admin', admin);
router.use('/wechat', wechat);
router.use('/message', message);
router.use('/group', group);
router.use('/contact', contact);
router.use('/material', material);
router.use('/file', file);
router.use('/keyword', keyword);
router.use('/information', information);
router.use('/tag', tag);
router.use('/information_tag', informationTag);
router.use('/auto_reply', autoReply);
router.use('/room_info', roomInformation);
router.use('/bulk_message', bulkMessage);
export default router;
